import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import Sidebar from "./_components/sidebar";
import Header from "./_components/header";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const {session} = await getUser()

    if(!session){
        return redirect('/dashboard/sign-in')
    }

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex h-screen w-full">
                    <Sidebar />
                    <div className="flex-1 flex flex-col">
                        <Header />
                        <main className="flex-1 p-6">{children}</main>
                    </div>
                </div>
            </body>
        </html>
    );
}
